[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
std = "c11"
hide-symbols = true

[build.cpp]
std = "c++20"
hide-symbols = true

[data]
plug = "bndl"
src = "source/data"
out = "target/sigmoid.bndl"

[sigmoid]
exe = "sigmoid"
lang = "cpp"
dyn-libs = [ "nwge", "nwge_cli", "SDL2" ]

[test_game]
plug = "bndl"
src = "source/game/test"
out = "target/games/test.bndl"
